import { Component, OnInit, OnDestroy, inject, AfterViewInit, HostListener } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { CommonModule } from '@angular/common';
import { Ticket } from './ticket.models';
import { FormsModule } from '@angular/forms';
import { Directive, EventEmitter, Input, Output } from '@angular/core';
import { AuthService } from '../../services/auth.service';
import { environment } from '../../../environments/environment.development';

export type SortColumn = keyof Ticket | '';
export type SortDirection = 'asc' | 'desc' | '';
const rotate: { [key: string]: SortDirection } = { asc: 'desc', desc: '', '': 'asc' };

//sort table elements
const compare = (v1: string | number | Date, v2: string | number | Date) => 
  (v1 < v2 ? -1 : v1 > v2 ? 1 : 0);
export interface SortEvent {
  column: SortColumn;
  direction: SortDirection;
}
@Directive({
  selector: 'th[sortable]',
  standalone: true,
  host: {
    '[class.asc]': 'direction === "asc"',
    '[class.desc]': 'direction === "desc"',
    '(click)': 'rotate()',
  },
})
export class NgbdSortableHeader {
  @Input() sortable: SortColumn = '';
  @Input() direction: SortDirection = '';
  @Output() sort = new EventEmitter<SortEvent>();
  rotate() {
    this.direction = rotate[this.direction];
    this.sort.emit({ column: this.sortable, direction: this.direction });
  }
}

@Component({
  selector: 'app-ticket-view',
  standalone: true,
  imports: [CommonModule, FormsModule, NgbdSortableHeader],
  templateUrl: './ticket-view.component.html',
  styleUrl: './ticket-view.component.scss'
})

export class TicketViewComponent implements OnInit, OnDestroy {
  //only logged in user can submit new ticket
  constructor(private authService: AuthService) {}
  get isLoggedIn(): boolean {
    return this.authService.isLoggedIn();
  }
  http = inject(HttpClient);
  //state variable
  tickets: Ticket[] = []; // Array to hold tickets
  filteredTickets: Ticket[] = []; // Array for filtered tickets
  searchTerm: string = ''; // Search term for filtering
  sortColumn: string = '';
  sortDirection: SortDirection = ''; // Updated to match SortDirection type
  user: any; // Placeholder for the logged-in user
  currentPage = 1;
  pageSize = 20;
  isLoading = false; // Loading state
  totalTickets = 0; // Total number of tickets available on the server
  
  //ticket form default values
  newTicket: Ticket = {
    _id: '', // This will be generated by the backend
    issuer: '', // Set issuer to the logged-in user's ID
    issuerName: '', // Set issuer name to the logged-in user's name
    name: '', // ticket name
    description: '',
    status: 'open', // Default status open
    createdAt: new Date() // This will be set by the backend
  };
  //Tab switching
  activeTab: 'tickets' | 'analytics' = 'tickets';
  switchTab(tab: 'tickets' | 'analytics'): void {
    this.activeTab = tab;
  }
  // Ticket crud modal 
  isModalVisible: boolean = false; // Modal visibility state
  editingTicket: Ticket | null = null; // Tracks the ticket being edited
  isViewModalVisible = false;
  viewingTicket: Ticket | null = null;

  //modal management
  openViewModal(ticket: Ticket): void {
    this.viewingTicket = ticket;
    this.isViewModalVisible = true;
  }
  closeViewModal(): void {
    this.viewingTicket = null;
    this.isViewModalVisible = false;
  }
  openModal(ticket?: Ticket): void {
    if (ticket) {
      // Editing an existing ticket
      this.editingTicket = { ...ticket }; // Clone the ticket to avoid direct mutation
    } else {
      // Creating a new ticket
      this.editingTicket = {
        _id: '', // This will be generated by the backend
        issuer: this.user?._id || '', // Set issuer to the logged-in user's ID
        issuerName: this.user?.name || '', // Set issuer name to the logged-in user's name
        name: '', // user name
        description: '',
        status: 'open', // Default status
        createdAt: new Date(), // This will be set by the backend
      };
    }
    this.isModalVisible = true;
  }
  // Close the modal
  closeModal(): void {
    this.isModalVisible = false;
    this.editingTicket = null;
  }

  onSort({ column, direction }: SortEvent): void {
    this.sortColumn = column;
    this.sortDirection = direction;

    if (direction === '') {
      // If no direction, reset to the original order
      this.filteredTickets = [...this.tickets];
    } else {
      // Sort the filteredTickets array
      this.filteredTickets.sort((a, b) => {
        const valueA = a[column as keyof Ticket];
        const valueB = b[column as keyof Ticket];

        if (valueA < valueB) {
          return direction === 'asc' ? -1 : 1;
        }
        if (valueA > valueB) {
          return direction === 'asc' ? 1 : -1;
        }
        return 0;
      });
    }
  }
  loadTickets(): void {
    if (this.isLoading || (this.totalTickets > 0 && this.tickets.length >= this.totalTickets)) return;
    this.isLoading = true;
    const url = `${environment.apiUrl}/tickets?page=${this.currentPage}&limit=${this.pageSize}`;
    this.http.get<{ tickets: Ticket[]; total: number }>(url).subscribe({
      next: (data) => {
        this.tickets = [...this.tickets, ...data.tickets]; // Append new tickets
        this.filteredTickets = [...this.tickets]; // Sync filteredTickets
        this.totalTickets = data.total; // Update total tickets count
        this.isLoading = false;
        this.currentPage++; // Increment page for the next request
      },
      error: (error) => {
        console.error('Error loading tickets:', error);
        this.isLoading = false;
      },
    });
  }
    @HostListener('window:scroll', [])
    onScroll(): void {
      if (
        window.innerHeight + window.scrollY >= document.body.offsetHeight &&
        !this.isLoading
      ) {
        this.loadTickets();
      }
    }
  onSearch(): void {
    const searchTermLower = this.searchTerm.toLowerCase();
    if (searchTermLower.length <= 3) {
      // If search term is 3 characters or less, reset filteredTickets to the original tickets
      this.filteredTickets = [...this.tickets];
      return;
    }
    // Make a GET request to the search endpoint
    const url = `${environment.apiUrl}/tickets/search?query=${encodeURIComponent(searchTermLower)}`;
    console.log('Search URL:', url); // Log the search URL for debugging
    console.log('Search term:', searchTermLower); // Log the search term for debugging
    this.http.get<Ticket[]>(url).subscribe({
      next: (data) => {
        this.filteredTickets = data; // Update filteredTickets with search results
        console.log('Search results:', data); // Log the search results for debugging
      },
      error: (error) => {
        console.error('Error searching tickets:', error);
      },
    });
  }

  viewTicket(ticketId: string): void {
    console.log('View ticket:', ticketId);
  }

  saveTicket(): void {
    if (this.editingTicket?._id) {
      // Update existing ticket
      const url = environment.apiUrl + "/tickets/" + this.editingTicket._id;
      this.http.put<Ticket>(url, this.editingTicket).subscribe({
        next: (response) => {
          console.log('Ticket updated:', response);
          const index = this.tickets.findIndex((t) => t._id === response._id);
          if (index !== -1) {
            this.tickets[index] = response; // Update the ticket in the list
            this.filteredTickets = [...this.tickets]; // Sync filteredTickets
          }
          this.closeModal(); // Close the modal after saving
        },
        error: (error) => {
          console.error('Error updating ticket:', error);
        },
      });
    } else {
      // Create new ticket
      const url = environment.apiUrl+'/tickets';
      const { _id, createdAt, ...ticketWithoutId } = this.editingTicket || {};
      this.http.post<Ticket>(url, ticketWithoutId).subscribe({
        next: (response) => {
          console.log('Ticket created:', response);
          this.tickets.unshift(response); // Add the new ticket to the front of the list
          this.filteredTickets = [...this.tickets]; // Sync filteredTickets
          this.closeModal(); // Close the modal after saving
          this.resetForm(); // Reset the form after saving
        },
        error: (error) => {
          console.error('Error creating ticket:', error);
        },
      });
    }
  }

  resetForm() {
    this.newTicket = {
      _id: '',
      issuer: this.user._id, // Set issuer to the logged-in user's ID
      issuerName: this.user.name, // Set issuer name to the logged-in user's name
      name: this.user.name, // Set name to the logged-in user's name
      description: '',
      status: 'open',
      createdAt: new Date()
    };
  }

  deleteTicket(ticketId: string) {
  const url = environment.apiUrl + '/tickets/' + ticketId;
  this.http.delete(url).subscribe({
    next: () => {
      console.log('Ticket deleted:', ticketId);
      this.tickets = this.tickets.filter((ticket) => ticket._id !== ticketId); // Remove the ticket
      this.filteredTickets = [...this.tickets]; // Sync filteredTickets
    },
    error: (error) => {
      console.error('Error deleting ticket:', error);
    }
  });
}
// pagenation function 
get totalPages(): number {
  return Math.ceil(this.filteredTickets.length / this.pageSize);
}

get paginatedTickets(): Ticket[] {
  const start = (this.currentPage - 1) * this.pageSize;
  return this.filteredTickets.slice(start, start + this.pageSize);
}

nextPage(): void {
  if (this.currentPage < this.totalPages) {
    this.currentPage++;
  }
}

prevPage(): void {
  if (this.currentPage > 1) {
    this.currentPage--;
  }
}


  // Example of a signal
  ngOnInit(): void {
    // fetch user profile if logged in
    if (this.isLoggedIn) {
      this.authService.getUserProfile().subscribe({
        next: (response) => {
          this.user = response.user; // Store the user object
          this.newTicket.issuer = this.user._id; // Set the issuer for new tickets
        },
        error: (error) => {
          console.error('Error fetching user profile:', error);
        },
      });
    }
    this.loadTickets();
  }
  ngAfterViewInit(): void {
  }
  ngOnDestroy(): void {
    // Cleanup logic here
    // console.log('TicketViewComponent destroyed');
  }
}
